-- forgeflow knowledge schema (engine-owned; regenerated by export).
PRAGMA foreign_keys=OFF;
DROP TABLE IF EXISTS code_objects;
CREATE TABLE code_objects (          -- registry of code locations
    id            INTEGER PRIMARY KEY,
    repo          TEXT NOT NULL,
    path          TEXT NOT NULL,         -- file path at repo root
    symbol        TEXT,                  -- function/class; NULL = whole file
    kind          TEXT NOT NULL,         -- function | file | subsystem
    first_seen_sha TEXT NOT NULL,
    last_seen_sha TEXT NOT NULL,         -- bumped when confirmed still present
    UNIQUE(repo, path, symbol)
);
DROP TABLE IF EXISTS items;
CREATE TABLE "items" (
    id            INTEGER PRIMARY KEY,
    key           TEXT UNIQUE NOT NULL,  -- stable dedup key
    source        TEXT NOT NULL,         -- which workflow/human/import produced it
    pattern       TEXT,                  -- generalized root-cause pattern id
    title         TEXT NOT NULL,
    detail        TEXT,                  -- evidence: repro path, observed output
    state         TEXT NOT NULL DEFAULT 'found',
    severity      TEXT,
    repo          TEXT NOT NULL,
    base_sha      TEXT,
    branch        TEXT,                  -- fix branch name once fixing
    pr_number     INTEGER,
    created_at    TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
DROP TABLE IF EXISTS transitions;
CREATE TABLE transitions (           -- append-only audit log
    id            INTEGER PRIMARY KEY,
    item_id    INTEGER NOT NULL REFERENCES "items"(id),
    from_state    TEXT NOT NULL,
    to_state      TEXT NOT NULL,
    event         TEXT NOT NULL,         -- machine event, e.g. 'evidence:build_green'
    evidence      TEXT,                  -- JSON: exit codes, probe diff, shas
    run_id        INTEGER REFERENCES runs(id),
    at            TEXT NOT NULL DEFAULT (datetime('now'))
);
DROP TABLE IF EXISTS patterns;
CREATE TABLE patterns (              -- graduated from items.pattern
    id            TEXT PRIMARY KEY,
    description   TEXT NOT NULL,
    review_lens   TEXT,                  -- text injected into review prompts
    grep_rule     TEXT,                  -- machine-checkable rule: a no-AI finder
    status        TEXT NOT NULL DEFAULT 'active',  -- active | retired
    escapes       INTEGER NOT NULL DEFAULT 0,      -- found later after review missed it
    catches       INTEGER NOT NULL DEFAULT 0       -- caught at review time
);
DROP TABLE IF EXISTS methods;
CREATE TABLE methods (               -- the oracle bench
    id            TEXT PRIMARY KEY,
    description   TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'candidate', -- candidate | active | exhausted
    trials        INTEGER NOT NULL DEFAULT 0,
    verified_yield INTEGER NOT NULL DEFAULT 0,     -- items that passed the repro gate
    last_used_round INTEGER
);
DROP TABLE IF EXISTS chains;
CREATE TABLE chains (                -- curated traced call-paths
    id            TEXT PRIMARY KEY,
    repo          TEXT NOT NULL,
    sha           TEXT NOT NULL,         -- validity pin; hops drift with code
    nodes         TEXT NOT NULL,         -- JSON: [{path, line, symbol}, ...]
    hop_invariants TEXT NOT NULL,        -- JSON: per-hop promise + rank
    yields        TEXT,                  -- JSON: finding keys this chain produced
    status        TEXT NOT NULL DEFAULT 'active'
);
DROP TABLE IF EXISTS readings;
CREATE TABLE readings (              -- what an agent learned, pinned
    id            INTEGER PRIMARY KEY,
    object_id     INTEGER NOT NULL REFERENCES code_objects(id),
    run_id        INTEGER REFERENCES runs(id),     -- provenance: which run read it
    sha           TEXT NOT NULL,         -- validity pin; object changed => stale
    summary       TEXT NOT NULL,         -- short digest for prompt injection
    facts         TEXT,                  -- JSON claims (invariants, callers, quirks)
    created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
DROP TABLE IF EXISTS regions;
CREATE TABLE regions (               -- explore surface map
    id            TEXT PRIMARY KEY,      -- a source subsystem path prefix
    repo          TEXT NOT NULL,
    dry_streak    INTEGER NOT NULL DEFAULT 0,      -- consecutive no-new explores
    cooldown_until_round INTEGER,
    leased_by_task INTEGER REFERENCES tasks(id)    -- disjointness: one explorer per region
);
DROP TABLE IF EXISTS coverage;
CREATE TABLE coverage (              -- hunt ledger: where we have looked
    object_id     INTEGER NOT NULL REFERENCES code_objects(id),
    workflow      TEXT NOT NULL,
    sha           TEXT NOT NULL,         -- tree state when swept
    probe_rev     TEXT,                  -- oracle version used
    outcome       TEXT NOT NULL,         -- clean | items:<n>
    swept_at      TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (object_id, workflow, sha)
);
DROP TABLE IF EXISTS implications;
CREATE TABLE implications (          -- finding <-> code mapping
    item_id    INTEGER NOT NULL REFERENCES "items"(id),
    object_id     INTEGER NOT NULL REFERENCES code_objects(id),
    role          TEXT NOT NULL,         -- root_cause | touched_by_fix | witness
    PRIMARY KEY (item_id, object_id, role)
);
DROP TABLE IF EXISTS lessons;
CREATE TABLE lessons (
    id            INTEGER PRIMARY KEY,
    task_kind     TEXT NOT NULL,         -- which task kinds this lesson applies to
    trigger       TEXT NOT NULL,         -- what situation activates it
    rule          TEXT NOT NULL,         -- the instruction injected into prompts
    provenance    TEXT,                  -- PR/incident it came from
    created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
DROP TABLE IF EXISTS egress;
CREATE TABLE egress (                -- everything ever sent out
    id            INTEGER PRIMARY KEY,
    kind          TEXT NOT NULL,         -- comment | pr_create | pr_update | label
    target        TEXT NOT NULL,         -- repo#pr / repo#issue
    body_sha      TEXT NOT NULL,
    body_path     TEXT NOT NULL,         -- archived copy of what was sent
    forge_id      TEXT,                  -- remote-side id once the send succeeds
    task_id       INTEGER REFERENCES tasks(id),
    at            TEXT NOT NULL DEFAULT (datetime('now'))
);
DROP TABLE IF EXISTS watermarks;
CREATE TABLE watermarks (            -- external cursor state
    scope         TEXT PRIMARY KEY,      -- e.g. 'pr_comments:<repo>'
    cursor        TEXT NOT NULL          -- last processed id, NOT a timestamp
);
