#!/usr/bin/env python3
"""Export the forgeflow DB's KNOWLEDGE as CHUNKED, git-friendly files.

One JSONL file per table (one row per line, stable primary-key order) plus a
`_schema.sql`. Growth is append-shaped: a new finding/reading adds a *line* to
one file — so git diffs stay tiny and no single file balloons over time. This
is NOT truncation (no knowledge is dropped); it's chunking. Operational/audit
and regenerable tables (events/tasks/task_steps/runs/embeddings/dash_control)
are omitted — the engine re-creates them empty on open. Rebuild: db_import.py.

  db_export.py [--db run/state/forgeflow.db] [--out data/knowledge]
"""
from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path

# what carries the campaign's accumulated knowledge (worth versioning)
KNOWLEDGE = ["code_objects", "findings", "transitions", "patterns", "methods",
             "chains", "readings", "regions", "coverage", "implications",
             "lessons", "egress", "watermarks"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default="run/state/forgeflow.db")
    ap.add_argument("--out", default="data/knowledge")
    a = ap.parse_args()

    c = sqlite3.connect(a.db)
    c.row_factory = sqlite3.Row
    have = {r[0] for r in c.execute(
        "SELECT name FROM sqlite_master WHERE type='table'")}
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)

    schema = ["-- forgeflow knowledge schema (engine-owned; regenerated by export).",
              "PRAGMA foreign_keys=OFF;"]
    manifest, total = {}, 0
    for t in KNOWLEDGE:
        if t not in have:
            continue
        ddl = c.execute("SELECT sql FROM sqlite_master WHERE type='table'"
                        " AND name=?", (t,)).fetchone()
        if not ddl or not ddl[0]:
            continue
        info = list(c.execute("PRAGMA table_info(%s)" % t))
        cols = [r[1] for r in info]
        pk = [r[1] for r in info if r[5]]
        order = ", ".join(pk) if pk else ", ".join(cols)   # stable diff order
        schema += ["DROP TABLE IF EXISTS %s;" % t, ddl[0].strip() + ";"]
        n = 0
        with (out / (t + ".jsonl")).open("w") as fh:
            for row in c.execute("SELECT * FROM %s ORDER BY %s" % (t, order)):
                fh.write(json.dumps({k: row[k] for k in cols},
                                    ensure_ascii=False, sort_keys=True) + "\n")
                n += 1
        manifest[t] = n
        total += n
    (out / "_schema.sql").write_text("\n".join(schema) + "\n")
    (out / "_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n")

    kb = sum(p.stat().st_size for p in out.glob("*")) / 1e3
    print("exported %d rows across %d tables -> %s/ (%.0f KB, one JSONL per table)"
          % (total, len(manifest), out, kb))


if __name__ == "__main__":
    main()
